In [4]:
import pandas as pd
import numpy as np

In [3]:
#!which python

In [5]:
votacion = pd.read_excel("../data/2024_10_Alcaldes_Datos_Eleccion.xlsx", sheet_name='votacion')
votacion_por_comuna = pd.read_excel("../data/2024_10_Alcaldes_Datos_Eleccion.xlsx", sheet_name='votacion_por_comuna')
participacion = pd.read_excel("../data/2024_10_Alcaldes_Datos_Eleccion.xlsx", sheet_name='participacion')
votantes = pd.read_excel("../data/2024_10_Alcaldes_Datos_Eleccion.xlsx", sheet_name='votantes')

votacion_2021 = pd.read_excel("../data/candidaturas_convencionales_gobernadores_alcaldes_y_concejales_2021.xlsx")

In [2]:
votacion_por_comuna.head()

NameError: name 'votacion_por_comuna' is not defined

In [14]:
votacion.head()

,Nro Región,Región,Circunscripción senatorial,Distrito,Comuna,Circunscripción electoral,Local,Mesa,Lista,Pacto,Partido,Nombres,Primer apellido,Segundo apellido,Votos,Cargo
0,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ALTO HOSPICIO,ANEXO DE COLEGIO SAN ANTONIO DE MATILLA,52,F,PARTIDO SOCIAL CRISTIANO E INDEPENDIENTES,PARTIDO SOCIAL CRISTIANO,FERNANDO,ORTEGA,ORTEGA,36.0,NaN
1,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ALTO HOSPICIO,ANEXO DE COLEGIO SAN ANTONIO DE MATILLA,52,H,CONTIGO CHILE MEJOR,PARTIDO DEMOCRATA CRISTIANO,PATRICIO ELIAS,FERREIRA,RIVERA,134.0,ALCALDE
2,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ALTO HOSPICIO,ANEXO DE COLEGIO SAN ANTONIO DE MATILLA,52,Z,CHILE VAMOS,RENOVACION NACIONAL,RAMON,GALLEGUILLOS,CASTILLO,100.0,NaN
3,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ALTO HOSPICIO,ANEXO DE COLEGIO SAN ANTONIO DE MATILLA,52,ZZI,INDEPENDIENTES,INDEPENDIENTES,TANYA JACQUELINE,PRECILLA,CRUZ,28.0,NaN
4,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ALTO HOSPICIO,ANEXO DE COLEGIO SAN ANTONIO DE MATILLA,52,NaN,NaN,NaN,VOTOS NULOS,NaN,NaN,32.0,NaN

In [ ]:
votacion[['Comuna', 'Cargo']].groupby(votacion['Comuna']).count()

In [24]:
votacion_por_comuna.head()

,Nro Región,Región,Circunscripción senatorial,Distrito,Comuna,Lista,Pacto,Partido,Nombres,Primer apellido,Segundo apellido,Votos,Cargo
0,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,F,PARTIDO SOCIAL CRISTIANO E INDEPENDIENTES,PARTIDO SOCIAL CRISTIANO,FERNANDO,ORTEGA,ORTEGA,5837,NaN
1,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,H,CONTIGO CHILE MEJOR,PARTIDO DEMOCRATA CRISTIANO,PATRICIO ELIAS,FERREIRA,RIVERA,20946,ALCALDE
2,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,Z,CHILE VAMOS,RENOVACION NACIONAL,RAMON,GALLEGUILLOS,CASTILLO,18557,NaN
3,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,ZZI,INDEPENDIENTES,INDEPENDIENTES,TANYA JACQUELINE,PRECILLA,CRUZ,5753,NaN
4,1,DE TARAPACA,CIRCUNSCRIPCION SENATORIAL 2,DISTRITO 2,ALTO HOSPICIO,NaN,NaN,NaN,VOTOS EN BLANCO,NaN,NaN,2470,NaN

In [6]:
regiones = votacion_por_comuna['Comuna'].dropna().unique()

In [7]:
regiones

array(['ALTO HOSPICIO', 'CAMIÑA', 'COLCHANE', 'HUARA', 'IQUIQUE', 'PICA',
       'POZO ALMONTE', 'ANTOFAGASTA', 'CALAMA', 'MARIA ELENA',
       'MEJILLONES', 'OLLAGUE', 'SAN PEDRO DE ATACAMA', 'SIERRA GORDA',
       'TALTAL', 'TOCOPILLA', 'ALTO DEL CARMEN', 'CALDERA', 'CHAÑARAL',
       'COPIAPO', 'DIEGO DE ALMAGRO', 'FREIRINA', 'HUASCO',
       'TIERRA AMARILLA', 'VALLENAR', 'ANDACOLLO', 'CANELA', 'COMBARBALA',
       'COQUIMBO', 'ILLAPEL', 'LA HIGUERA', 'LA SERENA', 'LOS VILOS',
       'MONTE PATRIA', 'OVALLE', 'PAIHUANO', 'PUNITAQUI', 'RIO HURTADO',
       'SALAMANCA', 'VICUÑA', 'CABILDO', 'CALERA', 'CALLE LARGA',
       'CATEMU', 'HIJUELAS', 'LA CRUZ', 'LA LIGUA', 'LIMACHE',
       'LLAY-LLAY', 'LOS ANDES', 'NOGALES', 'OLMUE', 'PANQUEHUE',
       'PAPUDO', 'PETORCA', 'PUCHUNCAVI', 'PUTAENDO', 'QUILLOTA',
       'QUILPUE', 'QUINTERO', 'RINCONADA', 'SAN ESTEBAN', 'SAN FELIPE',
       'SANTA MARIA', 'VILLA ALEMANA', 'ZAPALLAR', 'ALGARROBO',
       'CARTAGENA', 'CASABLANCA', 'CONCON', 'EL QUISCO', 'EL TABO',
       'ISLA DE PASCUA', 'JUAN FERNANDEZ', 'SAN ANTONIO', 'SANTO DOMINGO',
       'VALPARAISO', 'VIÑA DEL MAR', 'CODEGUA', 'COINCO', 'COLTAUCO',
       'DOÑIHUE', 'GRANEROS', 'MACHALI', 'MALLOA', 'MOSTAZAL', 'OLIVAR',
       'QUINTA DE TILCOCO', 'RANCAGUA', 'RENGO', 'REQUINOA', 'CHEPICA',
       'CHIMBARONGO', 'LA ESTRELLA', 'LAS CABRAS', 'LITUECHE', 'LOLOL',
       'MARCHIGUE', 'NANCAGUA', 'NAVIDAD', 'PALMILLA', 'PAREDONES',
       'PERALILLO', 'PEUMO', 'PICHIDEGUA', 'PICHILEMU', 'PLACILLA',
       'PUMANQUE', 'SAN FERNANDO', 'SANTA CRUZ', 'SAN VICENTE',
       'CONSTITUCION', 'CUREPTO', 'CURICO', 'EMPEDRADO', 'HUALAÑE',
       'LICANTEN', 'MAULE', 'MOLINA', 'PELARCO', 'PENCAHUE', 'RAUCO',
       'RIO CLARO', 'ROMERAL', 'SAGRADA FAMILIA', 'SAN CLEMENTE',
       'SAN RAFAEL', 'TALCA', 'TENO', 'VICHUQUEN', 'CAUQUENES', 'CHANCO',
       'COLBUN', 'LINARES', 'LONGAVI', 'PARRAL', 'PELLUHUE', 'RETIRO',
       'SAN JAVIER', 'VILLA ALEGRE', 'YERBAS BUENAS', 'CHIGUAYANTE',
       'CONCEPCION', 'CORONEL', 'FLORIDA', 'HUALPEN', 'HUALQUI', 'PENCO',
       'SAN PEDRO DE LA PAZ', 'SANTA JUANA', 'TALCAHUANO', 'TOME',
       'ALTO BIOBIO', 'ANTUCO', 'ARAUCO', 'CABRERO', 'CAÑETE', 'CONTULMO',
       'CURANILAHUE', 'LAJA', 'LEBU', 'LOS ALAMOS', 'LOS ANGELES', 'LOTA',
       'MULCHEN', 'NACIMIENTO', 'NEGRETE', 'QUILACO', 'QUILLECO',
       'SAN ROSENDO', 'SANTA BARBARA', 'TIRUA', 'TUCAPEL', 'YUMBEL',
       'ANGOL', 'COLLIPULLI', 'CURACAUTIN', 'ERCILLA', 'GALVARINO',
       'LAUTARO', 'LONQUIMAY', 'LOS SAUCES', 'LUMACO', 'MELIPEUCO',
       'PERQUENCO', 'PUREN', 'RENAICO', 'TRAIGUEN', 'VICTORIA', 'VILCUN',
       'CARAHUE', 'CHOLCHOL', 'CUNCO', 'CURARREHUE', 'FREIRE', 'GORBEA',
       'LONCOCHE', 'NUEVA IMPERIAL', 'PADRE LAS CASAS', 'PITRUFQUEN',
       'PUCON', 'SAAVEDRA', 'TEMUCO', 'TEODORO SCHMIDT', 'TOLTEN',
       'VILLARRICA', 'FRESIA', 'FRUTILLAR', 'LLANQUIHUE', 'LOS MUERMOS',
       'OSORNO', 'PUERTO OCTAY', 'PUERTO VARAS', 'PURRANQUE', 'PUYEHUE',
       'RIO NEGRO', 'SAN JUAN DE LA COSTA', 'SAN PABLO', 'ANCUD',
       'CALBUCO', 'CASTRO', 'CHAITEN', 'CHONCHI', 'COCHAMO',
       'CURACO DE VELEZ', 'DALCAHUE', 'FUTALEUFU', 'HUALAIHUE', 'MAULLIN',
       'PALENA', 'PUERTO MONTT', 'PUQUELDON', 'QUEILEN', 'QUELLON',
       'QUEMCHI', 'QUINCHAO', 'AYSEN', 'CHILE CHICO', 'CISNES',
       'COCHRANE', 'COYHAIQUE', 'GUAITECAS', 'LAGO VERDE', "O'HIGGINS",
       'RIO IBAÑEZ', 'TORTEL', 'ANTARTICA', 'CABO DE HORNOS(EX-NAVARINO)',
       'LAGUNA BLANCA', 'NATALES', 'PORVENIR', 'PRIMAVERA',
       'PUNTA ARENAS', 'RIO VERDE', 'SAN GREGORIO', 'TIMAUKEL',
       'TORRES DEL PAINE', 'LA GRANJA', 'MACUL', 'ÑUÑOA', 'PROVIDENCIA',
       'SAN JOAQUIN', 'SANTIAGO', 'LA REINA', 'LAS CONDES',
       'LO BARNECHEA', 'PEÑALOLEN', 'VITACURA', 'LA FLORIDA',
       'LA PINTANA', 'PIRQUE', 'PUENTE ALTO', 'SAN JOSE DE MAIPO',
       'EL BOSQUE', 'LA CISTERNA', 'LO ESPEJO', 'PEDRO AGUIRRE CERDA',
       'SAN MIGUEL', 'SAN RAMON', 'ALHUE', 'BUIN', 'CALERA DE TANGO',
       'CURACAVI', 'EL MONTE', 'ISLA DE MAIPO', 'MARIA PINTO',
       'MELIPILLA', 'PADRE HURTADO', 'PAINE', 'PEÑAFLOR', 'SAN BERNARDO',
       'SAN PEDRO', 'TALAGANTE', 'CERRILLOS', 'COLINA',
       'ESTACION CENTRAL', 'LAMPA', 'MAIPU', 'PUDAHUEL', 'QUILICURA',
       'TILTIL', 'CERRO NAVIA', 'CONCHALI', 'HUECHURABA', 'INDEPENDENCIA',
       'LO PRADO', 'QUINTA NORMAL', 'RECOLETA', 'RENCA', 'CORRAL',
       'FUTRONO', 'LAGO RANCO', 'LANCO', 'LA UNION', 'LOS LAGOS', 'MAFIL',
       'MARIQUINA', 'PAILLACO', 'PANGUIPULLI', 'RIO BUENO', 'VALDIVIA',
       'ARICA', 'CAMARONES', 'GENERAL LAGOS', 'PUTRE', 'BULNES',
       'CHILLAN', 'CHILLAN VIEJO', 'COBQUECURA', 'COELEMU', 'COIHUECO',
       'EL CARMEN', 'NINHUE', 'ÑIQUEN', 'PEMUCO', 'PINTO', 'PORTEZUELO',
       'QUILLON', 'QUIRIHUE', 'RANQUIL', 'SAN CARLOS', 'SAN FABIAN',
       'SAN IGNACIO', 'SAN NICOLAS', 'TREHUACO', 'YUNGAY'], dtype=object)

In [26]:
votacion_por_comuna[['Comuna', 'Cargo']].groupby(votacion_por_comuna['Comuna']).count()

                 Comuna  Cargo
Comuna
ALGARROBO             9      1
ALHUE                 6      1
ALTO BIOBIO           6      1
ALTO DEL CARMEN       7      1
ALTO HOSPICIO         6      1
...                 ...    ...
YUMBEL                6      1
YUNGAY                8      1
ZAPALLAR              5      1
ÑIQUEN                7      1
ÑUÑOA                 6      1

[346 rows x 2 columns]

In [27]:
votacion_por_comuna[votacion_por_comuna['Comuna']=='ALGARROBO']

,Nro Región,Región,Circunscripción senatorial,Distrito,Comuna,Lista,Pacto,Partido,Nombres,Primer apellido,Segundo apellido,Votos,Cargo
461,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,F,PARTIDO SOCIAL CRISTIANO E INDEPENDIENTES,INDEPENDIENTES,GASTON,DUBOURNAIS,RIVEROS,332,NaN
462,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,Z,CHILE VAMOS,RENOVACION NACIONAL,MARCO ANTONIO,GONZALEZ,CANDIA,4250,ALCALDE
463,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,ZZI,INDEPENDIENTES,INDEPENDIENTES,ALEJANDRO FELIPE,RICOTTI,SEPULVEDA,2425,NaN
464,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,ZZI,INDEPENDIENTES,INDEPENDIENTES,CARLOS ORLANDO,TAPIA,AVILES,1089,NaN
465,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,ZZI,INDEPENDIENTES,INDEPENDIENTES,MARCELA MARITZA,MANSILLA,POTOCNJAK,2677,NaN
466,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,ZZI,INDEPENDIENTES,INDEPENDIENTES,MARIA LUISA,HAMILTON,VELASCO,365,NaN
467,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,ZZI,INDEPENDIENTES,INDEPENDIENTES,VERONICA MARICEL,CUETO,CUETO,2905,NaN
468,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,NaN,NaN,NaN,VOTOS EN BLANCO,NaN,NaN,392,NaN
469,5,DE VALPARAISO,CIRCUNSCRIPCION SENATORIAL 6,DISTRITO 7,ALGARROBO,NaN,NaN,NaN,VOTOS NULOS,NaN,NaN,970,NaN

2025-05-16 18:59:43.800 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.894
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/loretoaguero/Desktop/ESTUDIO/_Proyectos/mujeres_en_elecciones/mujeres_env/lib/python3.9/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-05-16 18:59:43.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.905 Session state does not function when running a script without `streamlit run`
2025-05-16 18:59:43.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-16 18:59:43.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()